import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Menu from "@/components/menu";
import Sidebar from "@/components/sidebar";
import Whatsappbar from "@/components/whatsappbar";

import "./globals.css";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Whatsappbar />
        <div className={styles.container}>
          <Header />
          <Menu />
          <div className={styles.content}>
            <Sidebar />
            <div className={styles.children}>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
